name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  deploy-staging:
    name: Deploy / Staging
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Running step 1
        run: |
          echo "Running step 1"

      - name: Running step 2
        run: |
          echo "Running step 2"

      - name: Running step 3
        run: |
          echo "Running step 3"          

  deploy-review:
    name: Deploy / Review
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Running step 1
        run: |
          echo "Running step 1"

      - name: Running step 2
        run: |
          echo "Running step 2"

      - name: Running step 3
        run: |
          echo "Running step 3"          

  deploy-production:
    name: Deploy / Production
    runs-on: ubuntu-latest
    needs:
      - deploy-staging
    steps:
      - name: Running step 1
        run: |
          echo "Running step 1"

      - name: Running step 2
        run: |
          echo "Running step 2"

      - name: Running step 3
        run: |
          echo "Running step 3"          
